name: Daily Danawa Scraper

on:
  schedule:
    - cron: '0 15 * * *' # UTC 기준 15시 = 한국 밤 12시
  workflow_dispatch: # 내가 원할 때 수동으로 버튼 눌러서 실행 가능하게 함

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Node.js 세팅
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 프로그램 설치
        run: npm install

      - name: 크롤링 봇 실행!
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: node scraper.js
